# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Server
source:           ./
destination:      _site
host:             0.0.0.0
port:             4000
url:              http://getbootstrap-extras.com
encoding:         UTF-8

# Custom vars
current_version:  0.0.1
repo:             https://github.com/bsextras/bootstrap-extras

blog:             http://blog.getbootstrap-extras.com
expo:             http://expo.getbootstrap-extras.com

cdn:
  css:            https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css
  js:             https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js

github_username:  jtrumbull
